[www]
user = nobody
group = nobody
listen = 9000 ;this forces FastCGI to bind to a TCP socket rather than a local Unix file.

; When PHP-FPM boots up, it scrubs the entire system environment to prevent script hijacking.
clear_env = no ; Forces PHP-FPM to keep the environment variables active in memory.


; FastCGI Process Manager (FPM) settings
pm = dynamic ;it keeps a dynamic pool of persistent worker processes alive in the background.
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3