server {
    # 1. Listen on Port 443 for HTTPS (IPv4 & IPv6)
    listen 443 ssl;
    listen [::]:443 ssl;

    # 2. Server Domain Name
    server_name bchafi.42.fr;

    # 3. Cryptographic Keys (linking to the files we generated in Step 3)
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # 4. Enforce strict TLS versions (Inception Requirement)
    ssl_protocols TLSv1.2 TLSv1.3;

    # 5. Root Directory & Index Files
    root /var/www/html;
    index index.php index.html index.htm;

    # 6. URI Routing
    location / {
        try_files $uri $uri/ =404;
    }
}