events {}

http {
    # Server Block for HTTPS Configuration for each domain 
    # (bchafi.42.fr) and easly to do the same for other 100 domains
    server {
        # 1. Listen on Port 443 for HTTPS (IPv4 & IPv6)
        listen 443 ssl;
        listen [::]:443 ssl;

        # 2. Server Domain Name
        server_name nginx;

        # 3. Cryptographic Keys (linking to the files we generated in Step 3)
        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

        # 4. Enforce strict TLS versions (Inception Requirement)
        ssl_protocols TLSv1.2 TLSv1.3;

        # 5. Root Directory & Index Files
        root /var/www/html;
        # when you ask the server without specifying a file, it will look for these files in order
        index index.php index.html index.htm;

        # 6. URI Routing
        location / {
            try_files $uri $uri/ =404;
        }
        # # Catch any request ending in .php
        # location ~ \.php$ {
        #     # 1. Forward the request to the WordPress container on port 9000
        #     fastcgi_pass wordpress:9000;
            
        #     # 2. Include default FastCGI parameters for standard routing
        #     include fastcgi_params;
            
        #     # 3. Tell PHP-FPM exactly which file to execute
        #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # }
    }
}